### ISSUE TITLE
LocationConfirmation map throwing error if shown

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#362]
**What's wrong**
- map is not shown for any councils currently
- it throws an error about being unable to set property placeholder of undefined

**What done looks like**
- map should be shown and not throw errors

**Where the changes need to be made**
- LocationConfirmation.js

**Comment by mikahpinegar** [comment]
because the address bar doesn't exist, it's throwing an error when trying to set the placeholder

**Comment by mikahpinegar** [comment]
Cannot set properties of null (setting 'placeholder')
TypeError: Cannot set properties of null (setting 'placeholder')
    at setterFunc (http://localhost:3000/static/js/bundle.js:84917:78)
    at http://localhost:3000/static/js/bundle.js:84419:9

**Comment by mikahpinegar** [comment]
also remove conditional for not showing if MCCC is selected
